### PR TITLE
Add secret requirement to README

### PR DESCRIPTION
**Pull request by textbook**

### CODE REVIEW

**Comment by nelsonjchen** [comment]
OK, I'll put this in for now. However, I think a future version should use the built-in `GITHUB_TOKEN` functionality.

**Comment by textbook** [comment]
The `GITHUB_TOKEN` is an API token, so you'd have to totally change the way the push is being done, but otherwise ✅

**Comment by nelsonjchen** [comment]
It's not that hard to change. It's going to be one of those diffs that delete more than add which is nice.

https://github.com/nelsonjchen/mirror-zip-extract-push-action/blob/d750c8b1109d6f5e394321921747a5c76354f3bb/entrypoint.sh#L18

**Comment by nelsonjchen** [comment]
Nevermind, I thought it was easy but I evidently had chosen this path because of this:

https://github.com/maxheld83/ghpages/pull/18#issuecomment-485274829

I don't like PATs either. Those things are scoped to users, not repos. With keys, you can do per repo so it's a little safer. 

Darn. Oh well, I should document this in the README.

**Pull request merged**
